version: '3.9'
services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  mailhog:
    image: mailhog/mailhog:v1.0.1
    restart: unless-stopped
    ports:
      - "8025:8025"  # UI
      - "1025:1025"  # SMTP

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
      - mailhog
      - redis
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"
    command: ["java", "-jar", "/app/app.jar"]
    volumes:
      - ./keys:/app/keys
      - ./uploads:/app/uploads
      - ./tmp-uploads:/app/tmp-uploads

volumes:
  db_data:


