spring:
  application:
    name: sistema-java
  
  profiles:
    active: local
  
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML
  
  datasource:
    url: jdbc:h2:mem:sistema_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  
  data:
    # Redis Configuration (Embedded Redis for local development)
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
  
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: 67af468e706c8e
    password: c9c83240f6d045
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: false
  
  cache:
    type: redis
    redis:
      time-to-live: 600000

# Configurações da aplicação
app:
  rsa:
    keys:
      directory: ./keys

server:
  port: 8080
  servlet:
    context-path: /

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.sistema: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG