spring:
  application:
    name: sistema-java
  
  profiles:
    active: local
  
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML
  
  datasource:
    url: jdbc:h2:mem:sistema_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  
  data:
    # Redis Configuration (Embedded Redis for local development)
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
  
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: 67af468e706c8e
    password: c9c83240f6d045
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: false
        transport:
          protocol: smtp
    default-encoding: UTF-8
  
  cache:
    type: redis
    redis:
      time-to-live: 600000

# Configurações da aplicação
app:
  rsa:
    keys:
      directory: ./keys
  
  # Configurações de verificação de email
  email:
    enabled: true
    verification:
      url: "http://localhost:8080/verify-email"
      token:
        expiration:
          hours: 24
    
    # Configuração de provedor padrão
    default-provider: mailtrap
    
    # Configurações de fallback
    fallback:
      enabled: true
      provider: mailtrap
      
    # Configurações de retry para envio
    retry:
      enabled: true
      max-attempts: 3
      delay-ms: 2000
      backoff-multiplier: 2.0
      
    # Configurações de template
    templates:
      base-path: "classpath:/templates/email/"
      encoding: "UTF-8"
      cache-enabled: false
  
  # Configurações SMTP específicas
  smtp:
    # Configurações de retry
    retry:
      max-attempts: 3
      delay-ms: 1000
      backoff-multiplier: 2.0
    
    # Configurações de timeout
    timeout:
      connection-ms: 5000
      read-ms: 10000
      write-ms: 10000
    
    # Pool de conexões
    pool:
      max-connections: 10
      min-connections: 2
      idle-timeout-ms: 300000
    
    # Configurações de email padrão
    email:
      from: noreply@sistema.com
      reply-to: support@sistema.com
      bounce-address: bounce@sistema.com
      
    # Configurações de validação
    validation:
      test-email-on-startup: false
      validate-ssl-certificates: true
      connection-test-timeout-ms: 10000
    
    # Configurações por provedor
    providers:
      mailtrap:
        enabled: true
        host: sandbox.smtp.mailtrap.io
        port: 2525
        username: 67af468e706c8e
        password: c9c83240f6d045
        auth: true
        starttls: true
        ssl: false
        description: "Mailtrap - Ambiente de desenvolvimento para testes de email"
        from-email: "noreply@sistema.com"
      
      gmail:
        enabled: true
        host: smtp.gmail.com
        port: 587
        username: ${GMAIL_USERNAME:}
        password: ${GMAIL_APP_PASSWORD:fgsu vamy tghu ykiq}
        auth: true
        starttls: true
        ssl: false
        description: "Gmail SMTP - Produção com senha de aplicativo"
        from-email: ${GMAIL_FROM_EMAIL:sistema@gmail.com}
        properties:
          mail:
            smtp:
              ssl:
                trust: smtp.gmail.com
              socketFactory:
                class: javax.net.ssl.SSLSocketFactory
                fallback: false
      
      outlook:
        enabled: false
        host: smtp-mail.outlook.com
        port: 587
        username: ${OUTLOOK_USERNAME:}
        password: ${OUTLOOK_PASSWORD:}
        auth: true
        starttls: true
        ssl: false
        description: "Outlook/Hotmail SMTP"
        from-email: ${OUTLOOK_FROM_EMAIL:sistema@outlook.com}

server:
  port: 8080
  servlet:
    context-path: /

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

# Configurações de logging
logging:
  level:
    com.sistema: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.mail: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# Configurações específicas por ambiente
---
spring:
  config:
    activate:
      on-profile: development
      
app:
  email:
    default-provider: mailtrap
    smtp:
      validation:
        test-email-on-startup: true
        
logging:
  level:
    com.sistema: DEBUG
    org.springframework.mail: DEBUG

---
spring:
  config:
    activate:
      on-profile: production
      
app:
  email:
    default-provider: gmail
    smtp:
      validation:
        test-email-on-startup: false
        validate-ssl-certificates: true
        
logging:
  level:
    com.sistema: INFO
    org.springframework.mail: WARN
    org.hibernate.SQL: WARN