spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/sistema_db
    username: sistema_user
    password: sistema_pass
  
  data:
    redis:
      host: redis
      port: 6379
  
  mail:
    host: mailhog
    port: 1025

server:
  port: 8080

logging:
  level:
    com.sistema: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: INFO