spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: false
  
  h2:
    console:
      enabled: false
  
  redis:
    host: localhost
    port: 6379
    timeout: 2000ms
    database: 1
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  
  mail:
    host: smtp.mailtrap.io
    port: 587
    username: test_user
    password: test_pass
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

app:
  email:
    enabled: false
    provider: MAILTRAP
    from-email: test@sistema.com
  
  security:
    jwt:
      secret: test-secret-key-for-testing-purposes-only
      expiration: 3600000
  
  captcha:
    enabled: true
    length: 4
    expiration: 300

logging:
  level:
    com.sistema: WARN
    org.springframework: WARN
    org.hibernate: WARN
    org.testcontainers: OFF