spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/appdb
    username: app
    password: app
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  mail:
    host: localhost
    port: 1025
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis
  servlet:
    multipart:
      max-file-size: 6MB
      max-request-size: 6MB

    username: ""
    password: ""
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

app:
  security:
    jwt:
      secret: "this-is-a-very-long-and-secure-secret-key-change-me-please-1234567890"
      expiration: 3600000 # 1h ms
  frontendBaseUrl: "http://localhost:3000"
  uploadsDir: "uploads"
  uploadsTmpDir: "tmp-uploads"

server:
  port: 8080

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://db:5432/appdb
    username: app
    password: app
  mail:
    host: mailhog
    port: 1025
  data:
    redis:
      host: redis
      port: 6379


